# syntax=docker/dockerfile:1

FROM golang:1.21.3-alpine AS builder
RUN mkdir -p src/github.com/rturner3/spire-mysql-demo
WORKDIR /go/src/github.com/rturner3/spire-mysql-demo
COPY go.mod go.sum ./
RUN go mod download
COPY cmd cmd
COPY pkg pkg
RUN go build -o /sample-service ./cmd/sample-service

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian11 AS build-release-stage
WORKDIR /
COPY --from=builder /sample-service /sample-service
ENTRYPOINT ["/sample-service"]
