# syntax=docker/dockerfile:1

FROM golang:1.21.3-alpine AS builder
RUN mkdir -p src/github.com/rturner3/spire-mysql-demo
WORKDIR /go/src/github.com/rturner3/spire-mysql-demo
COPY go.mod go.sum .
RUN go mod download
COPY cmd cmd
RUN go build -o /tls-bootstrap ./cmd/mysql/tls-reload

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian11 AS build-release-stage
WORKDIR /
COPY --from=builder /tls-reload /tls-reload
ENTRYPOINT ["/tls-reload"]
